//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table
    {
        [Required]
        [Display(Name = "Flight ID")]
        public string Id { get; set; }
        [Required]
        [Display(Name = "Flight Number")]
        public int Flight { get; set; }

        [Required]
        public string Destination { get; set; }
        [Required]
        
        public System.DateTime STD { get; set; }

        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> ATD { get; set; }

        [Display(Name ="A/C Type")]
        public string A_C_Type { get; set; }

        [Display(Name = "A/C")]
        public Nullable<int> A_C { get; set; }
        public string Gate { get; set; }

         [Display(Name ="In Pad")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> In_Pad { get; set; }

        [Display(Name = "Start:")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Start_Spray_Type_1 { get; set; }

        [Display(Name = "Stop:")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Stop_Spray_Type_1 { get; set; }

        [Display(Name = "Gallons:")]
        public Nullable<int> Type_1_Gallons { get; set; }

        [Display(Name = "Start:")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Start_Spray_Type_4 { get; set; }

        [Display(Name = "Stop:")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Stop_Spray_Type_4 { get; set; }

        [Display(Name = "Gallons:")]
        public Nullable<int> Type_4_Gallons { get; set; }

        [Display(Name = "Out")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Out_Pad { get; set; }

        [Display(Name = "Precip")]
        public string Precipitation_Type { get; set; }

        [Display(Name = "Off")]
        [DisplayFormat(DataFormatString = "{0:t}")]
        public Nullable<System.DateTime> Off { get; set; }

        [Display(Name = "Runway")]
        public string Runway { get; set; }

        [Display(Name = "Out to In")]
        public Nullable<int> Out_to_In { get; set; }

        [Display(Name = "In to Out")]
        public Nullable<int> In_to_Out { get; set; }

        [Display(Name = "Type 1 Spray Time")]
        public Nullable<int> Type_1_Spray_Time { get; set; }

        [Display(Name = "Type 4 Spray Time")]
        public Nullable<int> Type_4_Spray_Time { get; set; }

        [Display(Name = "Total Spray Time")]
        public Nullable<int> Total_Spray_Time { get; set; }

        [Display(Name = "Hourly TP")]
        public Nullable<int> Hourly_TP { get; set; }

        [Display(Name = "Out to Off")]
        public Nullable<int> Out_to_Off { get; set; }

        [Display(Name = "Total Out to Off")]
        public Nullable<int> Total_Out_to_Off { get; set; }
        [DisplayFormat(DataFormatString = "{0:P2}")]
        [Display(Name = "Percent of Time to Pad")]
        public Nullable<int> Percent_of_Taxi_Time_to_Pad { get; set; }
        [DisplayFormat(DataFormatString = "{0:P2}")]
        [Display(Name = "Percent of Time on Pad")]
        public Nullable<int> Percent_of_Taxi_Time_On_Pad { get; set; }
        [DisplayFormat(DataFormatString = "{0:P2}")]
        [Display(Name = "Percent On Pad vs Spray Time")]
        public Nullable<int> Percent_On_Pad_vs_Spray_Time { get; set; }
        [DisplayFormat(DataFormatString = "{0:P2}")]
        [Display(Name = "Percent of Time from Pad to Takeoff")]
        
        public Nullable<int> Percent_of_Taxi_Time_From_Pad_to_Takeoff { get; set; }

        
    }
}
